name: flutter_refresh_indicator
description: "This package provides a refresh indicator widget that is far more flexible and native-like than the default Flutter one, built on top of flutter_appbar."
version: 1.2.0
publisher: ttankkeo112@gmail.com
repository: https://github.com/MTtankkeo/flutter_refresh_indicator

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appbar: ">=1.6.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
